language: php

branches:
  only:
    - master

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false
before_script:
  - composer install --prefer-dist

install:
  - travis_retry composer update

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --standard=PSR2 -n src/
